name: Keep Supabase Alive

on:
  schedule:
    - cron: "0 10 */3 * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping site
        run: curl https://fullstack-baber-shop.vercel.app/api/health
